### ISSUE TITLE
search should have spaces around query word

### ISSUE THREAD

**Issue by arnicas** [learntextvis/keyword-in-context#9]
In a word cloud, at least, the words are usually assumed to be space delimited.  the kwic search doesn't assume this, so the word cloud KWIC display is over-reporting.  Either add an option or change query to assume spaces around it?

**Comment by tafsiri** [comment]
Could you give an example? I'm not sure i understand the issue.

**Comment by arnicas** [comment]
Yes - this is the word "as" in a wordcloud, but the matches in the KWIC include intra-word hits:
![image](https://cloud.githubusercontent.com/assets/377341/12828349/45eb976e-cb52-11e5-8f68-bed37d4853e8.png)

**Comment by tafsiri** [comment]
ah okay. i'm initially inclined to make this fix in the word cloud (i.e. have the caller specify that as part of the query) rather than make it an explicit option. But i'll give it some more thought and see where I land.

**Comment by arnicas** [comment]
I'm ok with it in word cloud i think - just let me know, so i can dupe it into d3-word-cloud logic if you go that route.

**Comment by arnicas** [comment]
Let's punt on this and put it into the token string manually for the word-clouds. I'll file that against your word-cloud example, i did it in mine.
